### ISSUE TITLE
No codec provided to avcodec_open2()

### ISSUE THREAD

**Issue by cronke99** [dwbuiten/d2vsource#37]
Hello, I am testing Vapoursynth and d2vsource but having some problems. I have tested and I am pretty sure something is wrong with my script or compiled d2vsource

**Programs:**
```
Linux 4.18.0-0 (Debian 9)
Python 3.6
VS Core R45 built from latest git
Cython3 version 0.28.4
d2vsource built from latest git, built against ffmpeg below
x264 0.157.2935 545de2f
ffmpeg version N-47470-gfc94e9704e-static
```

**Script:**
```
import vapoursynth as vs
import functools
core = vs.get_core()

video = core.d2v.Source('source.ts.d2v')
video = core.std.Trim(video, 0, 1000)

video.set_output()
```
I made softlink to **/usr/local/lib/libd2vsource.so** inside **/usr/local/lib/vapoursynth**, and then I get this problem:
```
$ vspipe --y4m testing.vpy - | x264 --demuxer y4m - --output vs_test.mkv

[NULL @ 0x00000000] No codec provided to avcodec_open2()
Script evaluation failed:
Python exception: Cannot open decoder.

Traceback (most recent call last):
  File "src/cython/vapoursynth.pyx", line 1927, in vapoursynth.vpy_evaluateScript
  File "src/cython/vapoursynth.pyx", line 1928, in vapoursynth.vpy_evaluateScript
  File "testing.vpy", line 6, in <module>
    video = core.d2v.Source('source.ts.d2v')
  File "src/cython/vapoursynth.pyx", line 1833, in vapoursynth.Function.__call__
vapoursynth.Error: Cannot open decoder.
```
The same issue above happens even just checking the script with vspipe --info. I also tried remaking the .d2v with D2VWitch and they are identical files.

Source file is MPEG2 in .ts format. I wonder, what is it I am doing incorrect, or what might be broken?
Greetings and thanks for guidance!

**Comment by cronke99** [comment]
The problem was I was using ffmpeg and libavcodec build from Debian repositories. I built from source, no problems. You can use none or whatever selected configure flags, it seems OK either way. Some flags I used which maybe are important: --non-free --enable-shared
